### ISSUE TITLE
Error in jaeger query GRPC response

### ISSUE THREAD

**Issue by isgj** [timescale/promscale#1411]
I've configured promscale as a Jaeger data-source in grafana. When trying to query for a trace the promscale service returns `500`
In the logs I can see this message
```
caller=query.go:140 msg="Error in jaeger query GRPC response" err="scanning traces: error scanning trace: populate span error: making resource tags: unknown tag type []interface {}"
```

I'm using docker and the latest image.
The rest works well, it sends the data to the db and I can see all the APM dashboards in grafana.

**Comment by ramonguiu** [comment]
@isgj this issue should be fixed in the next release which we expect to come out next week.

See #1379

This is likely because you have a span attribute that is of type array. Could you run the following SQL query on the database to confirm?

`postgres=# select distinct jsonb_typeof(value) from _ps_trace.tag;`

**Comment by isgj** [comment]
Yes, I confirm there are tags of type array.
Thanks

![image](https://user-images.githubusercontent.com/20517048/171843743-18d702d6-a03d-4824-ab01-244ad12993eb.png)
