### ISSUE TITLE
Support continuous aggregates via PromQL

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#152]
Two things to research:
1) How do we expose the results of a continuous agg to the adapter for queries via PromQL 
2) What kind of aggregates do we want to support in continuous aggs. Specifically, do we need to support any of the prom aggregates? e.g. rate, increase, etc

**Comment by ksten-ab** [comment]
From my experience developing solutions based off of master, here are my thoughts:

1. Does it make sense for the connector to keep track of PromQL query statistics and automatically make some aggregates (e.g. for something like `increase[5m]`?  These could be saved/loaded from some `_prom_catalog.promql_aggregates` table that the connector can interrogate to know when it can use them.

2. Support for (at least) `delta` and `increase` would help significantly in helping materialize the results of otherwise fairly expensive queries.

**Comment by franck102** [comment]
Some feedback:

Pro

1. PromQL query stats would be completely irrelevant for us, we are using promscale to replace PromQL queries and their limitations (unwanted extrapolation of rate/increase over time ranges, no way to pre-compute rollups...)

2. Pre-defining aggregates would require knowing at least the type of the metric? Increase on a Gauge is meaningless, same for Average on a counter...

3. Our main issue right now is that the documented approach to deal with counter resets (using val - LAG(val)) cannot be used to define continuous aggregate views. See this issue: https://github.com/timescale/timescaledb/issues/2479

4. A promscale-generated data view containing sample-to-sample increases of Prom counters would resolve the above, and would be really valuable. Time period continuous aggregates could then easily be built on top of that.
Many Prometheus counters are completely useless unless counter resets can be accounted for.
