### ISSUE TITLE
Add telemetry event for Jaeger gRPC remote storage writer

### ISSUE THREAD

**Issue by arajkumar** [timescale/promscale#1548]
Relates to #1535

**Comment by arajkumar** [comment]
@VineethReddy02 We already have telemetry event around otel ingestion and #1535 is implemented on top of otel. Hence all the events which we send for otel ingestion is also applicable for Jaeger ingestion. Do we need any additional signal from the product perspective?

**Comment by VineethReddy02** [comment]
I agree with your point Arun, But we need to know if the user is using Otel or Jaeger ingestion endpoints or both? And rest all we can see from Otel-specific telemetry that has already been captured. Maybe it's a good idea to change telemetry keys from `otel` to `traces` to make it more generic. So that in telemetry the data points with `traces` represents traces in general i.e both Jaeger and Otel.

**Comment by arajkumar** [comment]
I've been exploring following options to enable telemetry,

1. Add metrics in WriteSpan and expose it to telemetry ( similar to e.g. https://github.com/timescale/promscale/blob/master/pkg/jaeger/store/store.go#L64)
2. Expose intrinsic metrics exposed by gRPC framework(grpc_server_handling_seconds_count{grpc_method="WriteSpan"})
3. Use [internal span attribute](https://github.com/jaegertracing/jaeger/pull/1493) populated by jaeger framework(internal.span.format=jaeger)

Option 1 and Option 2 requires changes in in promscale and extension, but 3 requires change only in extension.
