### ISSUE TITLE
Confusion about drop metrics

### ISSUE THREAD

**Issue by zongjiasushi** [timescale/promscale#1550]
Hi, promscale experts:

I am currently using delete_series HTTP API endpoint to drop the entire metrics.
I have 2 issues with this:

1. After I called this HTTP API, it seems that I can still see the underlying tables exists, even the data is empty. I called "VACCUM" manually but the tables are still there. When will the table be dropped?

2. I might immediately insert new data into the same metric name after I completely drop it using the delete_series HTTP API. Then I might have some errors from TimescaleDB logs:
a. **duplicate key value violates unique constraint**
b. **ERROR:  insert into a compressed chunk that has primary or unique constraint is not supported**

I suppose this is due to the delete_series API is non-blocking and actual deletion is still in progress. Can you point out when I can safely insert again? Thanks!

**Comment by Harkishen-Singh** [comment]
Hello @zongjiasushi , thank you for opening the issue!

1. The `/delete_series` API does not drop a metric. You could pass the metric name in a way to delete the metric, but Promscale does not delete the metric. It just removes all the series/data from that metric table. This is because deleting a table when Promscale connector is connected is dangerous as caches (and metric writers) in Promscale connector and database have some relationship. So, if you want to drop a metric completely, we recommend doing this through `SELECT prom_api.drop_metric('<metric_name>')` and it will remove the table as well. But note, this command will ask you to shutdown Promscale connector if any connector is running.
2. I tried to replicate this issue by making Prometheus write data and while it does, I deleted a complete metric using `curl -X POST -g 'http://localhost:9201/delete_series?match[]=go_memstats_lookups_total'`. I did not get any error in the ongoing ingestion.

> delete_series API is non-blocking

AFAIK, `/delete_series` is a blocking call ([relevant code](https://github.com/timescale/promscale/blob/5a3a365f7232bce2fdd97f28f46dfb60bafd2798/pkg/pgmodel/delete/delete.go#L41)). Can you provide more details on the error, like whether your setup involves HA, or try replicating again and mention the exact steps?

**Comment by zongjiasushi** [comment]
Thanks for the reply!
For 1, I understand the semantics but I wonder when are the metric tables (of the deleted metrics) are eventually garbage collected? What if we have a lot of different metrics (short lived, different names)? Would that cause any performance issues?

2. Yeah, it is not a persistent/consistent error. I think the error shows up when you do delete series first, then immediately write to the metric with the same name. The error only shows up when you re-insert the data again

**Comment by zongjiasushi** [comment]
Thanks!
