### ISSUE TITLE
insert with on conflict or returning clause is not supported on compressed chunks

### ISSUE THREAD

**Issue by doran-22** [timescale/promscale#1770]
**Describe the bug**
We are currently using promscale with OTL and we have an issue while inserting spans and events in promscale. To add more context we have a special use case of promscale where we have created a proxy that implement the export method, store the spans locally and then periodically (every 20 seconds) send them to promscale using the promscale export method. The service work perfectly during a certain time but after some time some spans and events start to fail :
```
level=error ts=2022-11-30T11:19:38.847Z caller=runner.go:61 msg="error in GRPC call" err="error inserting spans: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=error ts=2022-11-30T11:19:38.887Z caller=runner.go:61 msg="error in GRPC call" err="error inserting spans: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=error ts=2022-11-30T11:19:38.929Z caller=runner.go:61 msg="error in GRPC call" err="error inserting spans: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=error ts=2022-11-30T11:19:38.969Z caller=runner.go:61 msg="error in GRPC call" err="error inserting spans: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=error ts=2022-11-30T11:19:39.010Z caller=runner.go:61 msg="error in GRPC call" err="error inserting spans: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=error ts=2022-11-30T11:19:39.048Z caller=runner.go:61 msg="error in GRPC call" err="error inserting events: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks (SQLSTATE 0A000)"
level=info ts=2022-11-30T11:19:39.827Z caller=throughput.go:82 msg="ingestor throughput" spans/sec=8 spans-last-write-on=2022-11-30T11:19:38.841Z
```
We have tried to change the compression delay on promscale, we tried to disable it completly but nothing worked until now, do you have an hint on how to troubleshoot the problem or solve it?

**To Reproduce**
Hard to determine what causes the issue, it seems we try to insert too old spans.

Tell me if you need further informations!

**Comment by ramonguiu** [comment]
@doran-aisprid the way ingestion works is that data is written to chunks. Chunks store one hour worth of data. When recent data arrives that is out the time interval assigned to the current chunk, a new chunk is created and new data is written there.
Chunks that are not the current latest one are compressed in the background to save disk space.

At the moment, TimescaleDB where the data is stored does not support doing insert on conflict do nothing into compressed chunks. The TimescaleDB team is working to add support for that which I expect will be available in Q1.

In any case, you should not be having issues if you're always sending recent spans so it looks like there are some spans that are in the past.

I think we are waiting some time before compressing old chunks to cover for the case of late arriving data. I'm 100% sure we do it for metrics (we wait 1 hour since the last timestamp stored in chunk) but I am not sure how it works in tracing. @jgpruitt could you confirm?

**Comment by ramonguiu** [comment]
It's possible to patch your system so that it waits more time before data is compressed. Before we look into that, could you clarify how long do you expect them to be? What are those spans tracking? It's not very common to have spans that are so long.

So no spans are being ingested at all? If you have short spans that would be really weird if there are no errors. The following line seems to indicate that spans are actually being ingested:

> level=info ts=2022-11-30T11:19:39.827Z caller=throughput.go:82 msg="ingestor throughput" spans/sec=8 spans-last-write-on=2022-11-30T11:19:38.841Z

If you run the following SQL query, do you get any results?

`SELECT count(*) FROM ps_trace.span WHERE start_time > now() - interval '12h'`

**Comment by doran-22** [comment]
Our span can last from some milli-seconds to hours, we are tracking workflows that have direct impact on physical devices so we have really long spans (can be some hours). 
We have multiple devices that are actually sending spans to promscale so the log you are seeing come from this "healty services".
Yes after running your query I have some spans.

**Comment by doran-22** [comment]
Hello sorry for the delay, we set this value to 10 days and soon we will have some results so we can tell you if it fixed our issue. However we are really interested in the feature you talked about for Q1! :)

**Comment by ramonguiu** [comment]
@doran-22 has the error gone away?

**Comment by doran-22** [comment]
With a compression set to 10 days we didn't see any more occurence of the problem until now, I keep the thread open for some more days just to be sure as the delay may be a bit longer now with 10 days before compression!
