### ISSUE TITLE
Question: Is there a command to prune data for metrics?

### ISSUE THREAD

**Issue by KES777** [timescale/promscale#1782]
**Is your feature request related to a problem? Please describe.**

Database is growing and growing. Is there a command to prune data for old metrics?

**Describe the solution you'd like.**
`command pruneold --till=2022-03-07`

**Describe alternatives you've considered**
Would be nice also to have command to aggregate data. Eg. we have some metrics for every minute.
We can shrink data by aggregating it to one per hour or one per day. 

**How would this feature help you***
So we can still view last year, which load has CPU and this info do not took much space of storage.

**Comment by ramonguiu** [comment]
@KES777 Promscale automatically removes all data based on the configured retention period. By default the retention period for metrics is 3 months and for traces 1 month. You can see how to change them in [our documentation](https://docs.timescale.com/promscale/latest/manage-data/retention/).

Regarding your comment about aggregate data, we are currently working on a feature to generate automatic rollups for all your metrics so that you can keep raw data for a short period of time and aggregated data for a long period of time without incurring high disk storage usage.

Additionally, Timescale Cloud has recently announced support for data tiering to S3 in private beta providing "infinite" and very cost-efficient storage. In the future, S3 storage will also be available to Promscale users that use Timescale Cloud for storing their data, delivering big cost savings in storage.
