### ISSUE TITLE
Feature request: Having a way of knowing the size taken by the data for a period of time

### ISSUE THREAD

**Issue by fayak** [timescale/promscale#306]
As mentioned on Slack, I have an idea for a feature that could be useful, regarding data storage.

I'd like to know how much space is taken by my data, to make estimations and be able to plan storage amount, provision new disks, estimate backup sizes, etc.

This feature could be implemented by a function or and API call, and its parameters/output could be the following:
- Filter data by a label, and instance_id, etc
- Select a time frame, or all data
- Output the disk usage compressed and uncompressed

This doesn't seems to be a high priority feature though. Thanks !

**Comment by Harkishen-Singh** [comment]
We do have the asked data (like compressed, uncompressed sizes) in `timescaledb_information.compressed_hypertable_stats` and `timescaledb_information.hypertable` where details related to metrics data are available. Have you checked these?

Also, in order to plan the amount, wont `\l+ <timescaledb_name>` or `select pg_database_size('<timescaledb_name>');` be enough?

**Comment by cevian** [comment]
related to #346

**Comment by VineethReddy02** [comment]
closing this issue, as we haven’t received multiple requests from users for this feature and it's quite stale! :)

If you still have a need for this, Please open a new issue.

Thanks!
