### ISSUE TITLE
Better auto-upgrade policies for dependencies

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#329]
A few things to do (all up for discussion) 

- [x] Prevent auto-upgrades to extension versions higher than default version of extension
- [x] Prevent auto-upgrades across major versions (guarded by flag)
- [x] Prevent auto-upgrades to pre-release versions (guarded by flag; possibly with exception of default version?)
- [x] Have a catch-all auto-upgrade flag for all extensions
- [x] Make sure all CLI flags settable via helm (done?)
- [ ] Document production setting options 
    - use immutable docker tags (preferred I think)
    - turn off auto-upgrade

**Comment by franck102** [comment]
Hi, I would also suggest:
1. Having any upgrade turned off by default
2. Having installation and upgrades of the timescaledb extension turned off by default

I do understand the desire to make things easy for users, however with the current defaults the risk is high to see a properly tested solution deployed to a production environment, only to fail at a random later time as a new release of either extension is made available. IMHO promscale shouldn't ever try to modify the timescaledb extension: after all we don't expect the timescale installer to update Postgres, or the Postgres installer to upgrade Kubernetes :)

It is also not quite clear whether using a completely specified timescaledb image tag (timescaledb-single.image.tag) in the timescale-single chart would prevent the promscale go command from trying to upgrade the timescale extension?

**Comment by franck102** [comment]
Is there any proposed workaround for installing promscale today using helm?
The latest chart available from the repository, 0.1.1, doesn't support setting container args for the promscale container, so we cannot pass -install-timescaledb=false & -migrate=false, promscale upgrades tsdb to 2.0.0-rc2 and the deployment doesn't work.

I created a local copy of the latest promscale chart, specifying the arguments, and the promscale container now fails to start with this error:
`level=error ts=2020-11-09T07:28:42.988Z caller=runner.go:110 msg="aborting startup due to error" err="dependency error: db schema version is incorrect: expected 0.1.1, got 0.1.0-beta.5"`

Can the auto-install / auto-upgrade code in promscale be disabled until this is properly fixed? Promscale is currently breaking our TimescaleDB deployment, which is used by other services.

**Comment by franck102** [comment]
Trying to install with the  -install-timescaledb=false & -migrate=false args, against a fresh 1.7.4 timescaledb install, promscale fails to start with this message:

level=info ts=2020-11-09T13:20:55.340Z caller=runner.go:103 msg="Version:0.1.1; Commit Hash: "
level=info ts=2020-11-09T13:20:55.340Z caller=runner.go:104 config="&{ListenAddr::9201 TelemetryPath:/metrics PgmodelCfg:{Host:dms-timescaledb.dmp-monitoring.svc.cluster.local Port:5432 User:postgres password:**** Database:timescale SslMode:allow DbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} LogCfg:{Level:debug Format:logfmt} HaGroupLockID:0 RestElection:false PrometheusTimeout:-1ns ElectionInterval:5s Migrate:false StopAfterMigrate:false UseVersionLease:true CorsOrigin:^(?:.*)$ InstallTimescaleDB:false}"
level=info ts=2020-11-09T13:20:55.340Z caller=runner.go:197 msg="Skipping migration"
level=error ts=2020-11-09T13:20:55.426Z caller=runner.go:110 msg="aborting startup due to error" err="dependency error: failed to check schema version: Error getting DB version: ERROR: relation \"prom_schema_migrations\" does not exist (SQLSTATE 42P01)"

**Comment by cevian** [comment]
@franck102 your immediate issues are fixed by release 0.1.2. #338 which is part of that release will guarantee that the docker image `timescaledev/timescaledb-ha:pg12-ts1.7-latest` will stay on 1.7.x and never go above that. Apologies for this bug.

BTW your comment https://github.com/timescale/promscale/issues/329#issuecomment-724010817 does not work since migration is disabled but you need to migrate to install the initial schema on an empty database.

**Comment by franck102** [comment]
> @franck102 your immediate issues are fixed by release 0.1.2. #338 which is part of that release will guarantee that the docker image `timescaledev/timescaledb-ha:pg12-ts1.7-latest` will stay on 1.7.x and never go above that. Apologies for this bug.
> 
> BTW your comment [#329 (comment)](https://github.com/timescale/promscale/issues/329#issuecomment-724010817) does not work since migration is disabled but you need to migrate to install the initial schema on an empty database.

Thanks @cevian for the quick turn-around, we will test 0.1.2 right away.

**Comment by cevian** [comment]
note some work on this in #394

**Comment by franck102** [comment]
Thanks @cevian , looks like we are getting there 👍

**Comment by cevian** [comment]
Closing this for now as I think most critical issues are fixed. Feel free to re-open or file a new issue if I missed something
