### ISSUE TITLE
Feedback Wanted: Prometheus benchmarking feedback

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#391]
This is meant as a thread to share ideas of the best way to create an open, reproducible, and fair benchmarking suite for various long term stores in the Prometheus ecosystem.

Especially helpful would be pointers to open datasets with real-world prometheus data.

**Comment by cevian** [comment]
We do have a loader for prometheus data in tsbs https://github.com/timescale/tsbs/tree/master/cmd/tsbs_load_prometheus but we aren't quite happy with it for the following reasons:

**Comment by RichiH** [comment]
https://docs.google.com/document/d/12DcuwrHnR-gVbWQq2Qq5UI2ZIq5CqS7W3OYALU6Bke8 might be relevant to your interests.

**Comment by valyala** [comment]
I'd propose creating a dataset from real time series data collected from the most widely used exporters such as [node_exporter](https://github.com/prometheus/node_exporter/), which run under production load. Then this data could be ingested into various Prometheus-compatible remote storage systems at a fixed rate, while measuring resource usage during the benchmark (CPU, RAM, disk IO, disk space, network bandwidth). Something like in the following benchmarks:

* https://valyala.medium.com/promscale-vs-victoriametrics-resource-usage-on-production-workload-91c8e3786c03
* https://valyala.medium.com/prometheus-vs-victoriametrics-benchmark-on-node-exporter-metrics-4ca29c75590f

Then queries from the corresponding Grafana dashboards could be extracted and issued to the tested systems in order to measure resource usage during query processing.

**Comment by nethsix** [comment]
If possible the benchmarks should include query performance, e.g., extraction 1000 time-series that matches 2 labels over 6 hour time range with start/end time of 2021-01-01 00:00:00 to 2021-01-05 00:00:00.
