### ISSUE TITLE
promscale environment variables not respected in new docker-compose.yml

### ISSUE THREAD

**Issue by htsoi-boto** [timescale/promscale#409]
commit c1e72654938051a06fc36e8e1cc4afba70407817 where values changed from TS_PROM to PROMSCALE doesn't seem to take effect in environment variables.

prometheus_postgresql_adapter: restarts and docker logs output:

level=info ts=2020-12-31T03:49:23.832Z caller=client.go:54 msg="host=db port=5432 user=postgres dbname=timescale password='****' sslmode=allow connect_timeout=10" numCopiers=8 pool_max_conns=16 pool_min_conns=4

Reverting to the older values works with the adapter:

  promscale-connector:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
      - prometheus
    environment:
      PROMSCALE_LOG_LEVEL: debug
      PROMSCALE_DB_CONNECT_RETRIES: 10
      #PROMSCALE_DB_HOST: db
      TS_PROM_DB_HOST: db
      TS_PROM_DB_PASSWORD: postgres
      PROMSCALE_DB_PASSWORD: postgres
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      #PROMSCALE_DB_SSL_MODE: allow
      TS_PROM_DB_SSL_MODE: allow

**Comment by htsoi-boto** [comment]
[https://github.com/timescale/promscale/commit/c1e72654938051a06fc36e8e1cc4afba70407817#diff-5760aead5887edbf5189540adaedc0978c537b7173d5889f90cf8082cea8ce4a](url)

**Comment by VineethReddy02** [comment]
Hi @htsoi-boto 
The issue is you need to explicitly pull the image `docker pull timescale/promscale:latest` the `docker-compose up` uses an existing image if an image is available locally. As env prefix, name change from `TS_PROM` to `PROMSCALE` is released recently. Please pull the promscale explicitly and try using the `docker-compose.yml`.

Reverting to old env variables works because the image you are using locally is old(not a recent release). The latest release expects env variables to be PROMSCALE_*.

**Comment by cevian** [comment]
@htsoi-boto can you verify that this Vineeth's suggestion fixed your error

**Comment by htsoi-boto** [comment]
sorry for the delay. this now works with the latest pull and docker-compose from here:
https://raw.githubusercontent.com/timescale/promscale/master/build/docker-compose.yml
