### ISSUE TITLE
Promscale HA needed when only making remote write

### ISSUE THREAD

**Issue by deathwarrior60** [timescale/promscale#496]
Hello,

I have 4 prometheus having the same data. Each prometheus have a promscale instance.
My prometheus only write in promescale.
So since I have 4 promescale write the data in timescale, they find duplicate and they don't insert it.
` caller=duplicates.go:36 msg="duplicate data in sample" total-duplicate-metrics=2260`

To this point everything works fine, and works like I want it.

So my question is, in my usecase, do I need to setup the [promescaleHA](https://github.com/timescale/promscale/blob/master/docs/high-avaliability/prometheus-HA.md) ? What would be the advantage of setting it up ? or what are the risk of keeping my current setup ?

**Comment by Harkishen-Singh** [comment]
Hey @deathwarrior60 

Running multiple Promscales with duplicate data will work fine, but it can increase the load on the DB since the data being inserted is already present in the DB, so the insert query is still being performed even if you have data. This may bottleneck the DB in extreme cases. Please note that Promscale protects your data from duplicate inserts. 

> What would be the advantage of setting it up?

Setting up HA will prevent this, no matter how high your ingestion rate is. This is because when in HA mode, the Promscale will write only if the leader has died. This will decrease the current inserts by thrice, and your db would be happy.

> what are the risk of keeping my current setup ?

There isn't any risk, since promscale handles duplicates seriously, meaning duplicates will never be inserted into the DB. But if you take this to extreme ingestion rates, the DB may use high CPU due to repeated scanning of duplicate data during insertion, that is already present in the db. Another thing to note is, when you have multiple Prometheus writing data to a single storage, the data intervals might get irregular which means the time-based PromQL functions (like rate, irate, etc.) might deviate from accurate results

**Comment by deathwarrior60** [comment]
Thanks for this clear anwser.

Regards
