### ISSUE TITLE
Promscale setting PROMSCALE_DB_HOST in docker-compse is invalid, it is still localhost

### ISSUE THREAD

**Issue by XiaoyuZhann** [timescale/promscale#500]
![image](https://user-images.githubusercontent.com/38707400/108356109-a9eae780-7226-11eb-91cd-a183edfffe03.png)
![image](https://user-images.githubusercontent.com/38707400/108356163-c129d500-7226-11eb-964a-8761750414f6.png)
![image](https://user-images.githubusercontent.com/38707400/108356202-d0108780-7226-11eb-81de-bf29fa814fbf.png)

**Comment by cevian** [comment]
@VineethReddy02 can you please take a look?

**Comment by VineethReddy02** [comment]
Hi @XiaoyuZhann 
The logs of the Promscale say that you are using the Promscale version as **0.1.1**. This version is very old, IN Promscale 0.1.1 we do not support env variables as **PROMSCALE_*** this was introduced in Promscale version 0.1.4 (more precisely here is the [0.1.4 release changelog](https://github.com/timescale/promscale/releases/tag/0.1.4))

Please update the Promscale version to the [recent release](https://github.com/timescale/promscale/releases/tag/0.2.0) i.e. **0.2.0** as you are using docker-compose you need to explicitly pull the Promscale latest image. Docker always tries to use the local cached image with the **latest** tag in your case it's the **0.1.1** version of Promscale. 

For some reason, if you want to use the **0.1.1** version of Promscale (we do not recommend this, we suggest all our users use the latest versions of Promscale as the latest versions include new features & fixes to the issues noticed in older versions) use the env variable key as **TS_PROM_*** instead of **PROMSCALE_*** as the env key prefix in older versions was different.
