### ISSUE TITLE
prom-migrator: suggestions and new features

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#574]
Following are suggestions related to prom-migrator:

1. Make timeout configurable and based on that, add the respective behaviours:
1.1. -timeout: <duration> (related to context timeout
1.2. -on-timeout: ['ext', 'fail', 'retry'] (`exit` exits the prom-migrator which is the current behaviour; `fail` drops the slab and `retry` retries the request endlessly unless -max-retries is set to non-zero)
1.3. -max-retries: <integer> (default 0 for retrying forever, if recoverable error)
2. change `mint` & `maxt` to `start` & `end`
3. allow start & end (current mint & maxt) to accept human-readable time.

**Comment by mjf** [comment]
I would also add one feature (and corresponding option) for simple "rate limiting" so that we could limit the speed of ingestion into *PostgreSQL* that may easiily become highly overloaded by the `prom-migrator`...

There are already some options like `-max-read-size` and `-concurent-{push,pulls}` that can influence that. I propose to add

```sh
    -pull-push-delay DURATION
```

defaulting of course to `0` which would cause a `DURATION` delay between pull of the data and the push of them.
It also seems to me as the most straighforward and easiest way to implement some sort of "slowdown" in case it is needed.

*Note:* By the way, the option `-concurent-push` should be renamed to `-concurent-pushes` (plural).

**Comment by Harkishen-Singh** [comment]
Closing since these were implemented in the prom-migrator.
