### ISSUE TITLE
Promscale integartion with timescaleDB ext with Apache 2.0 liecense

### ISSUE THREAD

**Issue by raviranjanelastisys** [timescale/promscale#635]
Integration of PostgreSQL deployed via zalando operator  with timescaleDB extension ( Apache 2.0 ) does not support with Promscale .Can you fix it ?

![image](https://user-images.githubusercontent.com/75951259/119358177-ac872e00-bca8-11eb-8ab2-72217a88b6fe.png)

**Comment by Harkishen-Singh** [comment]
This has been in our backlog. We did a bit of discussion and thought to do some work on this on upcoming quarter due to tight plans right now.

However, would be awesome if you want to fix this and submit a PR for this. This will be an awesome help to the project as well. Let me know if you are interested, and I can try to help you with it.

**Comment by raviranjanelastisys** [comment]
Currently i have some time constraints  but will wait for your team to fix this .

**Comment by Harkishen-Singh** [comment]
#659 is a WIP PR for this issue.

**Comment by ramonguiu** [comment]
@raviranjanelastisys this issue was fixed a few weeks ago and released with Promscale 0.5.1. Please reopen the ticket if you are still seeing it after upgrading Promscale.
