### ISSUE TITLE
Add example on how to connect to an instance when you have a postgres connection string 

### ISSUE THREAD

**Issue by antekresic** [timescale/promscale#65]
We need to make it more clear in the helm charts documentation how to use it when you supply a connection string from an existing TimescaleDB instance.

**Comment by yuriysolovyov** [comment]
> We need to make it more clear in the helm charts documentation how to use it when you supply a connection string from an existing TimescaleDB instance.

**Comment by VineethReddy02** [comment]
In the Promscale 0.1.4 release, we added support for Promscale to connect to TimescaleDB using `--db-uri` flag.  
More details on the configuration with helm are documented [here](https://github.com/timescale/promscale/tree/master/helm-chart#prerequisites) and on regarding promscale flags are documented [here](https://github.com/timescale/promscale/blob/master/docs/cli.md#database-flags)

closing the issue as this is fixed in the last release.
